services:
#  softethervpn:
#    image: siomiz/softethervpn:alpine
#    hostname: softethervpn
#    restart: always
#    container_name: softethervpn
#    env_file: private/environment/softethervpn.env
#
#    logging:
#      driver: json-file
#      options:
#        max-size: "10m"
#        max-file: "5"
#
#    ports:
#      # OpenVPN, unused
#      # - "1194:1194/udp"
#      # L2TP/IPSec
#      - "500:500/udp"
#      # L2TP/IPSec
#      - "4500:4500/udp"
#      # L2TP/IPSec
#      - "1701:1701/tcp"
#      # SoftEther VPN Server
#      - "5555:5555/tcp"
#      # SoftEther VPN Server
#      - "992:992/tcp"
#
#    cap_add:
#      - NET_ADMIN
#
#    volumes:
#      # Don't store any logs
#      - /dev/null:/usr/vpnserver/server_log
#      - /dev/null:/usr/vpnserver/packet_log
#      - /dev/null:/usr/vpnserver/security_log

#  l2tp-ipsec-vpn:
#    image: hwdsl2/ipsec-vpn-server
#    restart: always
#    # VPN_IPSEC_PSK, VPN_USER, VPN_PASSWORD
#    env_file:
#      - private/environment/l2tp-ipsec-vpn.env
#    ports:
#      # L2TP/IPSec
#      - "500:500/udp"
#      # L2TP/IPSec
#      - "4500:4500/udp"
#    privileged: true
#    hostname: l2tp-ipsec-vpn
#    container_name: l2tp-ipsec-vpn
#    volumes:
#      - ./private/l2tp-ipsec-vpn:/etc/ipsec.d
#      - /lib/modules:/lib/modules:ro

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    network_mode: "bridge"
    container_name: wg-easy
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./private/wgeasy:/etc/wireguard
    # WG_HOST, PASSWORD_HASH variable
    env_file: private/environment/wgeasy.env
    restart: always
