services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    restart: always
    privileged: true
    user: root

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      # this is needed in order to monitor docker
      # to make it work you need to create user "zabbix" with id 1997 on the host system,
      # and make sure it has enough permissions to read /var/run/docker.sock, for that run scripts/create-zabbix-user.sh
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=Europe/Amsterdam
      - ZBX_HOSTNAME=hostname.of.your.monitored.host
      - ZBX_SERVER_HOST=hostname.domain
