
FROM nginx:alpine

LABEL name=paskal/terrty-nginx
LABEL maintainer="paskal.07@gmail.com"

COPY public /usr/share/nginx/html

COPY nginx/terrty.net.conf /etc/nginx/conf.d/default.conf
COPY nginx/theatrestudio.ru.conf /etc/nginx/conf.d/theatrestudio.ru.nginx.conf
COPY nginx/terrty.net.conf /etc/nginx/conf.d/default.conf
COPY /etc/letsencrypt /etc/letsencrypt
COPY /etc/nginx/dhparam.pem /etc/nginx/dhparam.pem
