name: pull

on:
  push:
    branches:
      - master

jobs:
  build-images:
    name: Pull code from master to terrty.net
    runs-on: ubuntu-latest

    steps:
      - name: pull newest code to terrty.net from master
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl https://hooks.terrty.net/update/pull-code/${UPDATER_KEY}
